- name: "install nginx"
  package:
       name: "{{package_name}}"
       state: present
  register: my_output
  changed_when: true

- name: "loop files"
  copy:
     src: "{{item}}"
     dest: /var/www/html/
  loop: "{{list}}"
  when:  my_output.changed == true 
  register: output
- name: " restart service"
  sysvinit:
     name: nginx
     state: restarted
  when: output.changed == true 
